spring: # spring.datasource.driver-class-name=com.mysql.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/hello_service
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    user: postgres
    schemas: hello_service
    password: password
